name: adhyayan
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'




dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3
  calendar_slider: ^0.0.4
  intl: ^0.19.0
  get: ^4.6.6
  zego_uikit_prebuilt_live_streaming: ^3.12.4
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_pdfviewer: ^26.2.11
  youtube_player_flutter: ^8.1.2
  flutter_localizations:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true

  generate : true

  assets:
    - assets/
    - assets/sub/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
